Resources:
  TableTempEmail:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'to'
          AttributeType: 'S'
        - AttributeName: 'sha256'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'to'
          KeyType: 'HASH'
        - AttributeName: 'sha256'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: temp-email
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  TableTempEmailSha256:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'to'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'to'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: temp-email-sha256
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  TableTempEmail:
    Value: !Ref TableTempEmail
    Export:
      Name: temp-email-table
  TableTempEmailSha256:
    Value: !Ref TableTempEmailSha256
    Export:
      Name: temp-email-table-sha256

  TableTempEmailArn:
    Value: !GetAtt TableTempEmail.Arn
    Export:
      Name: temp-email-tableArn
  TableTempEmailSha256Arn:
    Value: !GetAtt TableTempEmailSha256.Arn
    Export:
      Name: temp-email-table-sha256-arn
